ARG BASE
ARG BUILDER
ARG PLATFORM

FROM --platform=${PLATFORM} ${BUILDER} as builder
WORKDIR /spire
ADD ./ ./
RUN go mod download
RUN make bin/spire-agent

FROM --platform=${PLATFORM} ${BASE} as spire-agent
USER root
WORKDIR /spire
COPY --from=builder /spire/bin /spire/bin
RUN chmod 555 /spire/bin/*
ENTRYPOINT ["/spire/bin/spire-agent", "run"]
CMD []
